name: ChatFilterMC
version: '${project.version}'
main: mctest.chatfiltermc.ChatFilterMC
api-version: '1.20'

commands:
  filter:
    description: Modify the chat filter.
    usage: /mcchatfilter
    aliases: mcf, cf
    permission: filter
    permission-message: You do not have permission to run this command.
permissions:
  filter:
    description: Allows the user to modify the chat filter and receive automated messages when someone triggers filter.
    default: op
  filter.exception:
    description: Makes the user an exception to the filter.
    default: op